### ISSUE TITLE
Both 'restart' and 'start' action not working on openstack centos7 machine 

### ISSUE THREAD

**Issue by divyanshugarg** [goblin23/chef-spring-boot#3]
I am building Openstack VM using Centos7 image. My all others cookbooks are working perfectly.
But when I use to run this cookbook, it ran successfully till 'action run' but It try to execute either 'restart' or 'start' action, it failed with below message:

* execute[/usr/bin/systemctl daemon-reload] action run
       - execute /usr/bin/systemctl daemon-reload 
 * service[ReceiveService] action start
     - start service service[ReceiveService]
FATAL: Check if --bootstrap-protocol and --image-os-type is correct. closed stream
ERROR: IOError: Check if --bootstrap-protocol and --image-os-type is correct. closed stream

Other details:
1- it should read bootstrap-protocol as 'ssh' and image-os-type as 'linux'
2- It is a systemd service on Centos7.x machine.

**Comment by EtienneK** [comment]
Seems there is an issue when trying to reload systemd.
What happens when you run `/usr/bin/systemctl daemon-reload` on the machine, manually?

**Comment by divyanshugarg** [comment]
When I run 'systemctl daemon-reload' command, does not give me any error on console. **BUT** when I run **'systemctl status ReceiveService.service**', it give me some error which is not clear to me. I am able to run same application manually on the same machine using the same (ExecStart) command without any error. 

[cloud-user@receiveservicejava ~]$ **java -version**
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-b15)
OpenJDK 64-Bit Server VM (build 25.111-b15, mixed mode)
[cloud-user@receiveservicejava ~]$ **sudo systemctl status ReceiveService.service**
● ReceiveService.service - ReceiveService
   Loaded: loaded (/etc/systemd/system/ReceiveService.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2017-01-16 03:24:15 CST; 4min 29s ago
  Process: 8009 ExecStart=/usr/bin/java -Xmx512m -Xms256m -jar /opt/spring-boot/ReceiveService/ReceiveService.jar --server.port=8015 --logging.path=/opt/spring-boot/ReceiveService/logs --spring.application.name=ReceiveService (code=exited, status=1/FAILURE)
Main PID: 8009 **(code=exited, status=1/FAILURE)**

Jan 16 03:24:13 receiveservicejava java[8009]: 03:24:13,576 |-INFO in ch.qos.logback.classic.joran.action.Logger...false
Jan 16 03:24:13 receiveservicejava java[8009]: 03:24:13,576 |-INFO in ch.qos.logback.core.joran.action.AppenderR...gger]
Jan 16 03:24:13 receiveservicejava java[8009]: 03:24:13,577 |-INFO in ch.qos.logback.core.joran.action.AppenderR...gger]
Jan 16 03:24:13 receiveservicejava java[8009]: 03:24:13,577 |-INFO in ch.qos.logback.classic.joran.action.RootLo... WARN
Jan 16 03:24:13 receiveservicejava java[8009]: 03:24:13,577 |-INFO in ch.qos.logback.core.joran.action.AppenderR...ROOT]
Jan 16 03:24:13 receiveservicejava java[8009]: 03:24:13,577 |-INFO in ch.qos.logback.classic.joran.action.Config...tion.
Jan 16 03:24:13 receiveservicejava java[8009]: 03:24:13,578 |-INFO in ch.qos.logback.classic.joran.JoranConfigur...point
Jan 16 03:24:15 receiveservicejava systemd[1]: ReceiveService.service: main process exited, code=exited, status=...ILURE
Jan 16 03:24:15 receiveservicejava systemd[1]: Unit ReceiveService.service entered failed state.
Jan 16 03:24:15 receiveservicejava systemd[1]: ReceiveService.service failed.
Hint: Some lines were ellipsized, use -l to show in full.


[cloud-user@receiveservicejava ~]$ **/usr/bin/java -Xmx512m -Xms256m -jar /opt/spring-boot/ReceiveService/ReceiveService.jar --server.port=8015 --logging.path=/opt/spring-boot/ReceiveService/logs --spring.application.name=ReceiveService**
03:29:26,087 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
03:29:26,088 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
03:29:26,088 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/opt/spring-boot/ReceiveService/ReceiveService.jar!/BOOT-INF/classes!/logback.xml]
.
.
.
03:29:27,056 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
03:29:27,057 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@30dae81 - Registering current configuration as safe fallback point


  .   ____          _            __ _ _
/\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
\\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
=========|_|==============|___/=/_/_/_/
:: Spring Boot ::        (v1.4.2.RELEASE)

**Comment by goblin23** [comment]
Should be fixed by https://github.com/goblin23/chef-spring-boot/pull/13
